services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  commander:
    build: ./commander
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      REDIS_ADDR: redis:6379  # Connect to Redis container via internal DNS.
      WORKER_BOOTSTRAP_SECRET: bootstrapsecret # Password needed by workers to request tokens.
      TOKEN_TTL_SECS: "30" # Token lifespan
      COMMANDER_PORT: "8080"
    ports:
      - "8080:8080"

  worker1:
    build: ./worker
    depends_on:
      rabbitmq:
        condition: service_healthy
      commander:
        condition: service_started
      redis:
        condition: service_started
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      COMMANDER_URL: http://commander:8080
      REDIS_ADDR: redis:6379
      WORKER_BOOTSTRAP_SECRET: bootstrapsecret
      WORKER_ID: "soldier-1"
      WORKER_CONCURRENCY: "2"

  worker2:
    build: ./worker
    depends_on:
      rabbitmq:
        condition: service_healthy
      commander:
        condition: service_started
      redis:
        condition: service_started
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      COMMANDER_URL: http://commander:8080
      REDIS_ADDR: redis:6379
      WORKER_BOOTSTRAP_SECRET: bootstrapsecret
      WORKER_ID: "soldier-2"
      WORKER_CONCURRENCY: "2"

  worker3:
    build: ./worker
    depends_on:
      rabbitmq:
        condition: service_healthy
      commander:
        condition: service_started
      redis:
        condition: service_started
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      COMMANDER_URL: http://commander:8080
      REDIS_ADDR: redis:6379
      WORKER_BOOTSTRAP_SECRET: bootstrapsecret
      WORKER_ID: "soldier-3"
      WORKER_CONCURRENCY: "2"

  frontend:
    build: ./frontend
    depends_on:
      commander:
        condition: service_started
    ports:
      - "3000:80"
    environment:
      - REACT_APP_COMMANDER_URL=http://localhost:8080
